### PR TITLE
Add GitHub Service

### PR DESCRIPTION
**Pull request by brayniverse**
This pull request adds the GitHub API to your list of available services.

Quite simple to add new services actually, so if you'd like me to add some more I don't mind doing so.

### CODE REVIEW

**Comment by kdocki** [comment]
Can you check and make sure this isn't an issue? If that is resolved everything else looks awesome...

**Comment by brayniverse** [comment]
Thanks for pointing that out kdocki, I've fixed the typo and committed to this pull request.

**Comment by mgufrone** [comment]
anyway, i've got a problem using Github service on Linux. This package use "github" in lowercase, meanwhile the for the service called as "GitHub", which could make a problem on calling the class.

**Comment by brayniverse** [comment]
I'm having difficulty interpreting your problem, it's clearly to do with the naming of the package services. I was conforming to the convention set by the existing services. Can you please elaborate on your problem, maybe explain what problem you experience calling the class?

**Comment by mgufrone** [comment]
While i call `Social::login('github')`, i got error message. It says that `Call to a member function getAuthorizationUri() on a non-object` . That's why i create pull request on #9

**Pull request merged**
